/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainMenu;

import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sun.security.util.Password;

/**
 *
 * @author ASUS
 */
public class Register extends javax.swing.JFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pat = null;
    
    public Register() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        this.setTitle("GameCenter All of Games are Here!");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_repass = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_username = new javax.swing.JLabel();
        TxtUsername = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        RegistBtn = new javax.swing.JButton();
        TxtPassword = new javax.swing.JPasswordField();
        txtpassword2 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jlabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/left-arrow.png"))); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 40, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setText("Register");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 100, 50));

        lbl_email.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 250, 20));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Password");
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel1KeyPressed(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 100, -1));

        lbl_repass.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lbl_repass.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_repass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 250, 20));

        lbl_password.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 250, 20));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Re-type password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 130, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 250, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 250, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("E-mail.@yahoo.com");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 140, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 250, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 250, 10));

        lbl_username.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 250, 20));

        TxtUsername.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TxtUsername.setText("Username");
        TxtUsername.setBorder(null);
        TxtUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtUsernameMouseClicked(evt);
            }
        });
        TxtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtUsernameKeyPressed(evt);
            }
        });
        jPanel1.add(TxtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 250, 30));

        txtemail.setBorder(null);
        txtemail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtemailMouseClicked(evt);
            }
        });
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtemailKeyPressed(evt);
            }
        });
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 250, 20));

        RegistBtn.setBackground(new java.awt.Color(51, 198, 29));
        RegistBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        RegistBtn.setForeground(new java.awt.Color(255, 255, 255));
        RegistBtn.setText("Register");
        RegistBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RegistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistBtnActionPerformed(evt);
            }
        });
        jPanel1.add(RegistBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 80, -1));

        TxtPassword.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TxtPassword.setBorder(null);
        TxtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtPasswordMouseClicked(evt);
            }
        });
        TxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPasswordActionPerformed(evt);
            }
        });
        TxtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(TxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 250, -1));

        txtpassword2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtpassword2.setBorder(null);
        txtpassword2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpassword2MouseClicked(evt);
            }
        });
        txtpassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassword2ActionPerformed(evt);
            }
        });
        txtpassword2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpassword2KeyPressed(evt);
            }
        });
        jPanel1.add(txtpassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 250, -1));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 30, 20));

        jlabel8.setBackground(new java.awt.Color(255, 255, 255));
        jlabel8.setForeground(new java.awt.Color(255, 255, 255));
        jlabel8.setText("Sign in");
        jlabel8.setOpaque(true);
        jPanel1.add(jlabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 310, 370));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/STEAM.png.3228d01e2cfac78e14af570fd080815d.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1360, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistBtnActionPerformed
        if(TxtUsername.getText().equals("")) {
            lbl_username.setText("Username is empty!");
            
        }
        if(TxtPassword.getText().equals("")) {
            lbl_password.setText("Password is empty!");
        }
        if(txtpassword2.getText().equals("")) {
            lbl_repass.setText("Password is empty!");
        }
        if(txtemail.getText().equals("")) {
            lbl_email.setText("Email is empty!");
        }
        else{
   String uname=TxtUsername.getText();
   String upass=String.valueOf(TxtPassword.getPassword());
   String re_pass=String.valueOf(txtpassword2.getPassword());
   String email=txtemail.getText();
   
   PreparedStatement ps;
   String query="INSERT INTO Game.Login(Username,Password,Retype_Password,Email) values (?,?,?,?)";
        try {
            ps=MyConnection.getConnection().prepareStatement(query);
            
            ps.setString(1, uname);
            ps.setString(2, upass);
            ps.setString(3, re_pass);  
            ps.setString(4, email);
                        
            if(ps.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null, "New User add!");
                lbl_username.setText("");
                lbl_password.setText("");
                lbl_repass.setText("");
                lbl_email.setText("");
            }
            else{
            JOptionPane.showMessageDialog(null, "Data Can't be Empty!");
            }
            // TODO add your handling code here:
            //String Username,Password,ee;
            //Username=TxtUsername.getText();
            //Password=TxtPassword.getText();
            
            //if(Username.equals("admin")&& Password.equals("admin")){
            //JOptionPane.showMessageDialog(null, "Username and Password Matched!");}
            //else{
            //JOptionPane.showMessageDialog(null, "Username and Password do not Matched!");}
        } catch (SQLException ex ) {
            JOptionPane.showMessageDialog(null, "koneksi gagal!");
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    }//GEN-LAST:event_RegistBtnActionPerformed

    private void TxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPasswordActionPerformed

    private void TxtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtPasswordMouseClicked
        jLabel1.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_TxtPasswordMouseClicked

    private void TxtUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtUsernameMouseClicked
        TxtUsername.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_TxtUsernameMouseClicked

    private void txtpassword2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpassword2MouseClicked
        jLabel7.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_txtpassword2MouseClicked

    private void txtpassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassword2ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        hide();
        LoginDesign ld = new LoginDesign();
        ld.show();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void txtemailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtemailMouseClicked
    jLabel8.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        LoginDesign db = new LoginDesign();
        db.show();
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void TxtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtUsernameKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_TAB) {TxtUsername.setText("");}
    }//GEN-LAST:event_TxtUsernameKeyPressed

    private void jLabel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyPressed
        
    }//GEN-LAST:event_jLabel1KeyPressed

    private void TxtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPasswordKeyPressed
        jLabel1.setVisible(false);
    }//GEN-LAST:event_TxtPasswordKeyPressed

    private void txtpassword2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassword2KeyPressed
        jLabel7.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassword2KeyPressed

    private void txtemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyPressed
        jLabel8.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailKeyPressed

    /**
     * @param args the command line arguments
     */
    
    

    
    






     
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegistBtn;
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel jlabel8;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_repass;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtpassword2;
    // End of variables declaration//GEN-END:variables

   
    
}
