package MainMenu;

import Entities.Suppliers;
import com.sun.imageio.plugins.png.RowFilter;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import Configuration.Connect;


public class Supplier extends javax.swing.JFrame {
    Suppliers su = new Suppliers();
    Connect Conf_Con = new Connect();
    
    
    public Supplier() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        warning1.setVisible(false);
        warning2.setVisible(false);
        txsp_id.setText(autogeneratedID());
        Show_Supplier();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }
    public ArrayList<User>userList(){
        ArrayList<User>userList=new ArrayList<>();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=GameStore;integratedSecurity=true";
            String Username = "";
            String Password = "";
            Connection con = DriverManager.getConnection(url,Username,Password);
            String query="SELECT * FROM Game.Supplier";
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(query);
            User user;
            while(rs.next()){
                user=new User(rs.getString("Supplier_ID"),rs.getString("Supplier_Name"),rs.getString("Email"));
                userList.add(user);
            }
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        return userList;
        }
    
    public void Show_Supplier(){
            ArrayList<User>list=userList();
            DefaultTableModel model =(DefaultTableModel) Display_Supplier.getModel();
            Object[] row = new Object[3];
            for(int i=0;i<list.size();i++){
                row[0]=list.get(i).SID();
                row[1]=list.get(i).SName();
                row[2]=list.get(i).SEmail();
                model.addRow(row);
                }
            }
        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txcari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txsp_id = new javax.swing.JTextField();
        warning2 = new javax.swing.JLabel();
        txsp_name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txsp_email = new javax.swing.JTextField();
        sp_add = new javax.swing.JButton();
        sp_delete = new javax.swing.JButton();
        warning1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Display_Supplier = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        lbl_Title1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        lbl_Title = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1380, 576));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txcari.setBackground(new java.awt.Color(149, 149, 149));
        txcari.setForeground(new java.awt.Color(255, 255, 255));
        txcari.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txcariKeyReleased(evt);
            }
        });
        getContentPane().add(txcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 450, 30));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Supplier_ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Supplier_Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, -1, -1));

        txsp_id.setBackground(new java.awt.Color(82, 82, 82));
        txsp_id.setForeground(new java.awt.Color(255, 255, 255));
        txsp_id.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(txsp_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 270, 30));

        warning2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        warning2.setForeground(new java.awt.Color(255, 0, 0));
        warning2.setText("!");
        getContentPane().add(warning2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 30, 20));

        txsp_name.setBackground(new java.awt.Color(82, 82, 82));
        txsp_name.setForeground(new java.awt.Color(255, 255, 255));
        txsp_name.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(txsp_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 270, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("@Gmail.com");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 140, 40));

        txsp_email.setBackground(new java.awt.Color(82, 82, 82));
        txsp_email.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txsp_email.setForeground(new java.awt.Color(255, 255, 255));
        txsp_email.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txsp_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txsp_emailActionPerformed(evt);
            }
        });
        getContentPane().add(txsp_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 290, 30));

        sp_add.setBackground(new java.awt.Color(51, 204, 0));
        sp_add.setForeground(new java.awt.Color(255, 255, 255));
        sp_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus.png"))); // NOI18N
        sp_add.setText("Add");
        sp_add.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sp_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sp_addActionPerformed(evt);
            }
        });
        getContentPane().add(sp_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 110, 30));

        sp_delete.setBackground(new java.awt.Color(255, 0, 51));
        sp_delete.setForeground(new java.awt.Color(255, 255, 255));
        sp_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel-button.png"))); // NOI18N
        sp_delete.setText("Delete");
        sp_delete.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sp_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sp_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(sp_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 120, 30));

        warning1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        warning1.setForeground(new java.awt.Color(255, 0, 0));
        warning1.setText("!");
        getContentPane().add(warning1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 35, -1));

        Display_Supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier_ID", "Supplier_Name", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Display_Supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Display_SupplierMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Display_Supplier);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 520, 190));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magnifying-glass-finder.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 280, 50, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 270, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 270, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 270, 10));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 190, 10));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 190, 10));

        lbl_Title1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lbl_Title1.setForeground(new java.awt.Color(153, 153, 153));
        lbl_Title1.setText("Baljid Game Store");
        getContentPane().add(lbl_Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 230, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game-controller.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 160, -1, 67));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/left-arrow.png"))); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 40, 30));

        lbl_Title.setBackground(new java.awt.Color(153, 153, 153));
        lbl_Title.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Title.setForeground(new java.awt.Color(153, 153, 153));
        lbl_Title.setText("Supplier Form");
        getContentPane().add(lbl_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coding-isometric-07-150x150.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 220, 270));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 940, 160));

        jLabel7.setBackground(new java.awt.Color(109, 109, 109));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 570, 300));

        jLabel6.setBackground(new java.awt.Color(82, 82, 82));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 940, 300));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cropped-47891.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setPreferredSize(new java.awt.Dimension(1360, 768));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public String autogeneratedID(){
    
    String code = null;
    ResultSet rs = null;
    
    try {
        Conf_Con.ConnectionConn();
        Statement stm = Conf_Con.con.createStatement();
        String aut = "select top 1 Supplier_ID from Game.Supplier order by Supplier_ID desc";
        rs = stm.executeQuery(aut);
        if(rs.next()){
            code = rs.getString(1);
            int value = Integer.parseInt(code.substring(1));
            value++;
            if(value>=100){
            code = "S"+value;
            }
            else if(value>=10){
            code = "S0"+value;
            }
            else{
            code = "S00"+value;
            }
        }
        else {
            code = "S001";
        }  
    } catch (Exception e)  {
        System.out.println(e.getMessage());
    }
    return code;
    
}

private void getData() {
        try {
            su.Suppliers_ID = txsp_id.getText();
            su.Suppliers_Name = txsp_name.getText();
            su.Suppliers_Email = txsp_email.getText();
            
        }
        catch(Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        
    }

private void deleteData() {
        this.getData();
        int flag = this.validasi();
        if(flag == 0) {
            int i = su.doDelete();
            if(i == 0) {
                JOptionPane.showMessageDialog(null,"Data Gagal DiHapus!");
            }
            else {
                JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus!");
            }
        }
    }

 private int validasi() {
        int flag = 0;
        if(txsp_id.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"ID tidak boleh kosong!");
            flag = 1;
        }
        if(txsp_name.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Nama tidak boleh kosong!");
            flag = 1;
        }
	if(txsp_email.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Email tidak boleh kosong!");
            flag = 1;
            
        }
        return flag;
        
    }
 
 
    private void sp_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sp_addActionPerformed
        
        if(txsp_email.getText().contains("@gmail.com")) {
            warning2.setVisible(true);
        }
        if(txsp_name.getText().equals("")) {
            warning1.setVisible(true);
        }
        if(txsp_email.getText().equals("")) {
            warning2.setVisible(true);
        }

        else{
            String sp_id=txsp_id.getText();
            String sp_name=txsp_name.getText();
            String sp_email=txsp_email.getText()+"@gmail.com";
           
            PreparedStatement ps;
            String query="INSERT INTO Game.Supplier(Supplier_ID,Supplier_Name,Email) values (?,?,?)";
            try {
                ps=MyConnection.getConnection().prepareStatement(query);
            
                ps.setString(1, sp_id);
                ps.setString(2, sp_name);
                ps.setString(3, sp_email);
            
                if(ps.executeUpdate()>0 )
                {
                    JOptionPane.showMessageDialog(null, "New Supplier add!");
                    this.dispose();
                    Supplier sp = new Supplier();
                    sp.show();
                }
            else{
            JOptionPane.showMessageDialog(null, "Data Can't be empty");
            }
              } catch (SQLException ex ) {
            JOptionPane.showMessageDialog(null, "Connection Failed!");
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
    }//GEN-LAST:event_sp_addActionPerformed

    private void sp_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sp_deleteActionPerformed
        this.deleteData();
        this.dispose();
        Supplier sp = new Supplier();
        sp.show();        // TODO add your handling code here:
    }//GEN-LAST:event_sp_deleteActionPerformed

    private void Display_SupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Display_SupplierMouseClicked
        String SID =Display_Supplier.getValueAt(Display_Supplier.getSelectedRow(), 0).toString();
        String SName=Display_Supplier.getValueAt(Display_Supplier.getSelectedRow(), 1).toString();
        String SEmail=Display_Supplier.getValueAt(Display_Supplier.getSelectedRow(), 2).toString();
        jLabel10.setVisible(false);
        txsp_id.setText(SID);
        txsp_name.setText(SName);
        txsp_email.setText(SEmail);
        //int  i = Display_Supplier.getSelectedRow();
        //DefaultTableModel Model = (DefaultTableModel)Display_Supplier.getModel();
        //System.out.println(i);
        
       // txsp_id.setText(Model.getValueAt(i, 0).toString());
       // txsp_name.setText(Model.getValueAt(i, 1).toString());
       // txsp_email.setText(Model.getValueAt(i, 2).toString());
    }//GEN-LAST:event_Display_SupplierMouseClicked

    private void txsp_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txsp_emailActionPerformed
                    // TODO add your handling code here:
    }//GEN-LAST:event_txsp_emailActionPerformed

    private void txcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txcariKeyReleased

        DefaultTableModel table = (DefaultTableModel)Display_Supplier.getModel();
        String search = txcari.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        Display_Supplier.setRowSorter(tr);
        tr.setRowFilter(javax.swing.RowFilter.regexFilter(search));
            // TODO add your handling code here:
    }//GEN-LAST:event_txcariKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Dashboard db = new Dashboard();
        db.show();
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Display_Supplier;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JLabel lbl_Title1;
    private javax.swing.JButton sp_add;
    private javax.swing.JButton sp_delete;
    private javax.swing.JTextField txcari;
    private javax.swing.JTextField txsp_email;
    private javax.swing.JTextField txsp_id;
    private javax.swing.JTextField txsp_name;
    private javax.swing.JLabel warning1;
    private javax.swing.JLabel warning2;
    // End of variables declaration//GEN-END:variables
}
